// customer/src/components/Login.jsx
import React, { useState } from 'react';
import './Login.css';
import { useNavigate } from 'react-router-dom';

function Login() {
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState('');
    const navigate = useNavigate();

    const handleSubmit = (e) => {
        e.preventDefault();
        if (username === 'Adarsh Sidnal' && password === 'Ada') {
            alert('Login successful!');
            navigate("/Shop");
        } else {
            setError('Invalid username or password');
        }
    };

    return (
        <div className="Login">
            <h2>Login</h2>
            <form onSubmit={handleSubmit}>
                <div className="form-group">
                    <label htmlFor="username">Username:</label>
                    <input
                        type="text"
                        id="username"
                        value={username}
                        onChange={(e) => setUsername(e.target.value)}
                    />
                </div>
                <div className="form-group">
                    <label htmlFor="password">Password:</label>
                    <input
                        type="password"
                        id="password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                    />
                </div>
                {error && <div className="error">{error}</div>}
                <button type="submit">Login</button>
            </form>
        </div>
    );
}

export default Login;

// app/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrl: './login.component.css'
})
export class LoginComponent {

  constructor(private router: Router) { }

  loginData = {
    email: '',
    password: ''
  };

  login() {
    if (this.loginData.email === "Adarsh" && this.loginData.password === "Ada") {
      alert("Login Successfull");
      this.router.navigate(['/shop']);
    } else {
      alert("Invalid");
   }
    console.log('Login Data:', this.loginData);
  }
}

<form (ngSubmit)="login()">
    <div>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" [(ngModel)]="loginData.email" required>
    </div>
    <div>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" [(ngModel)]="loginData.password" required>
    </div>
    <button type="submit">Login</button>
</form>
